/* AUTO-GENERATED by scripts/seed.mjs — do not edit by hand.
   Run `npm run seed` to refresh from the live channel feed. */
window.AIMAN_SEED = {
  channel: {
    id: "UCyNphkU24SEmtyE6HblN1dg",
    name: "Aiman & Minal",
    handle: "https://www.youtube.com/@aimankhanofficial05",
    url: "https://www.youtube.com/channel/UCyNphkU24SEmtyE6HblN1dg",
    joined: "",
    country: "Pakistan",
    subscribers: null,
    views: null,
    videoCount: 15,
  },
  videos: [
    {
      id: "jBZUQgr61r4",
      title: "Birthday 🎂 🥳 #shorts",
      publishedAt: "2026-09-26T11:29:24+00:00",
      isShort: true,
    },
    {
      id: "pCNKQO_3r6E",
      title: "See how BnB skincare is made! From factory to your shelf.🧴✨ Buy now: bodynbody.com #shorts",
      publishedAt: "2026-09-25T16:06:05+00:00",
      isShort: true,
    },
    {
      id: "6TjbQI--zNM",
      title: "A little soft glam, a touch of elegance, and a whole lot of love for this look! ✨#shorts",
      publishedAt: "2026-09-24T07:00:07+00:00",
      isShort: true,
    },
    {
      id: "I52u4cLnpaI",
      title: "Me = trying to record a nice moment meanwhile aiman🤪#funny #shorts",
      publishedAt: "2026-09-23T20:32:59+00:00",
      isShort: true,
    },
    {
      id: "bIMmkN30JhU",
      title: "Minal Khan’s Stunning Co-Ord Set ✨ #MinalKhan #SammyK #Fashion #CoOrdSet #Style #Shorts",
      publishedAt: "2026-09-19T11:30:42+00:00",
      isShort: true,
    },
    {
      id: "e6mtb5oxQHA",
      title: "In love with this look! The color & makeup giving fall bride vibes 🤏🏻 🍂#shorts #minalkhan",
      publishedAt: "2026-09-17T14:53:04+00:00",
      isShort: true,
    },
    {
      id: "Trt3HlXhG0Q",
      title: "Transition Time with gorgeous and fav Minal Khan♥️ #shorts",
      publishedAt: "2026-09-16T20:55:03+00:00",
      isShort: true,
    },
    {
      id: "r9QAoEvt2Mg",
      title: "Oh dam ☕️#shorts",
      publishedAt: "2026-09-13T07:00:54+00:00",
      isShort: true,
    },
    {
      id: "wZg_8ozmy5E",
      title: "A celebration of craftsmanship, heritage and the art of bridal couture. ✨#shorts",
      publishedAt: "2026-09-13T06:11:25+00:00",
      isShort: true,
    },
    {
      id: "qaESiOPyTEA",
      title: "Shiny skin glossy glam & big bouncy hair aimankhan serving looks 💎🌸 💄#shorts",
      publishedAt: "2026-09-12T20:28:23+00:00",
      isShort: true,
    },
    {
      id: "TH8ndxbTEbI",
      title: "Nabila’s Clifton Branch #hairextensions #hairstyles #haircut #colourpopcosmetic @nabilasaloon",
      publishedAt: "2026-09-05T04:25:31+00:00",
      isShort: false,
    },
    {
      id: "uIMBqD_eBgQ",
      title: "Eira— Available Now ✨ MK Festive ’26 Timeless Grace. Festive Glamour. Intricate Handwork♥️#shorts",
      publishedAt: "2026-09-03T08:52:57+00:00",
      isShort: true,
    },
    {
      id: "0gF7ue9HV1g",
      title: "Aiman Khan♥️#shorts",
      publishedAt: "2026-08-21T06:01:27+00:00",
      isShort: true,
    },
    {
      id: "q6lPG7zQOow",
      title: "Happy Birthday Pakistan 🇵🇰 #shorts #14august #independenceday indep",
      publishedAt: "2026-08-16T05:33:57+00:00",
      isShort: true,
    },
    {
      id: "E_u1bzyL6L8",
      title: "Aiman Khan ♥️#shorts",
      publishedAt: "2026-08-07T11:40:50+00:00",
      isShort: true,
    },
  ],
};
