#!/usr/bin/env node
/* ============================================================================
   SEED REFRESHER
   ----------------------------------------------------------------------------
   Channel ka RSS feed pull karta hai aur `js/seed-videos.js` ko regenerate
   karta hai — taake website bina API key ke bhi fresh content dikhaye.

   Run:  node scripts/seed.mjs
   Ya:   npm run seed
   ========================================================================== */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const CHANNEL_ID =
  process.env.CHANNEL_ID || "UCyNphkU24SEmtyE6HblN1dg";
const FEED = `https://www.youtube.com/feeds/videos.xml?channel_id=${CHANNEL_ID}`;
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const decode = (s = "") =>
  s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(+n))
    .replace(/&amp;/g, "&");

const pick = (block, tag) =>
  decode((block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`)) || [])[1] || "");

const escapeJs = (s) => JSON.stringify(s);

console.log(`→ Fetching feed for ${CHANNEL_ID} …`);

const res = await fetch(FEED, { headers: { "User-Agent": UA } });
if (!res.ok) {
  console.error(`✗ Feed fetch failed: HTTP ${res.status}`);
  process.exit(1);
}
const xml = await res.text();

const channelName = pick(xml, "title") || "Aiman & Minal";

const videos = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(([, block], i) => {
  const id = pick(block, "yt:videoId");
  const title = pick(block, "title");
  const publishedAt = pick(block, "published");
  // Feed description se #shorts tag pakadte hain; warna 60s rule API par chalti hai
  const desc = pick(block, "media:description");
  const isShort = /#shorts?\b/i.test(`${title} ${desc}`);
  return `    {
      id: ${escapeJs(id)},
      title: ${escapeJs(title)},
      publishedAt: ${escapeJs(publishedAt)},
      isShort: ${isShort},
    },`;
});

if (!videos.length) {
  console.error("✗ Feed se koi video nahi mili. Channel private ya khaali ho sakta hai.");
  process.exit(1);
}

const out = `/* AUTO-GENERATED by scripts/seed.mjs — do not edit by hand.
   Run \`npm run seed\` to refresh from the live channel feed. */
window.AIMAN_SEED = {
  channel: {
    id: ${escapeJs(CHANNEL_ID)},
    name: ${escapeJs(channelName)},
    handle: "https://www.youtube.com/@aimankhanofficial05",
    url: ${escapeJs(`https://www.youtube.com/channel/${CHANNEL_ID}`)},
    joined: "",
    country: "Pakistan",
    subscribers: null,
    views: null,
    videoCount: ${videos.length},
  },
  videos: [
${videos.join("\n")}
  ],
};
`;

writeFileSync(join(ROOT, "js", "seed-videos.js"), out, "utf8");
console.log(`✓ Wrote js/seed-videos.js — ${videos.length} videos, ${videos.filter((v) => v.includes("true")).length} shorts.`);
